### ISSUE TITLE
Complete movies.md

### ISSUE THREAD

**Issue by aranas** [aranas/Git_Workshop_Collab2022#2]
You will be working on the movies.md file. Your job is to collect some awesome movie recommendations!

Create a new line in the file with:
your name + your favourite movie + emoji

[Here you can find a list of emoji markdown codes](https://gist.github.com/rxaviers/7360908)

- [ ] Sophie

**Comment by ashleyrblake** [comment]
Ashley Shawshank Redemption :)

**Comment by daniela-palleschi** [comment]
-[] Daniela

**Comment by morgane-prl** [comment]
- [] Morgane

**Comment by CasCoopmans** [comment]
- [ ] Cas

**Comment by morgane-prl** [comment]
-[] Morgane

**Comment by morgane-prl** [comment]
- [ ] Morgane

**Comment by pratik-bhandari** [comment]
- [ ] Pratik
